{
	"version": 1699528138,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bear1-sheet0.png",
		"images/bear2-sheet0.png",
		"images/cat1-sheet0.png",
		"images/cat2-sheet0.png",
		"images/cat3-sheet0.png",
		"images/cat4-sheet0.png",
		"images/cat5-sheet0.png",
		"images/cat6-sheet0.png",
		"images/cow-sheet0.png",
		"images/dog1-sheet0.png",
		"images/dog2-sheet0.png",
		"images/dog2-sheet1.png",
		"images/monkey1-sheet0.png",
		"images/monkey2-sheet0.png",
		"images/monkey2-sheet1.png",
		"images/mouse1-sheet0.png",
		"images/mouse2-sheet0.png",
		"images/panda-sheet0.png",
		"images/rabbit1-sheet0.png",
		"images/rabbit1-sheet1.png",
		"images/rabbit2-sheet0.png",
		"images/rabbit2-sheet1.png",
		"images/rabbit3-sheet0.png",
		"images/sheep-sheet0.png",
		"images/spr_menubg-sheet0.png",
		"images/btn_play-sheet0.png",
		"images/btn_volume-sheet0.png",
		"images/btn_volume-sheet1.png",
		"images/btn_shop-sheet0.png",
		"images/spr_bg-sheet0.png",
		"images/spr_bg-sheet1.png",
		"images/spr_bg-sheet2.png",
		"images/foods-sheet0.png",
		"images/foods-sheet1.png",
		"images/btn_home-sheet0.png",
		"images/carrots_icon-sheet0.png",
		"images/spr_scroll-sheet0.png",
		"images/btn_unlock-sheet0.png",
		"images/hidden_position-sheet0.png",
		"images/spritefont.png",
		"images/spr_game_title-sheet0.png",
		"images/spr_flowers-sheet0.png",
		"images/spr_flowers-sheet1.png",
		"images/spr_cloud-sheet0.png",
		"images/spr_butterfly-sheet0.png",
		"images/destroyer-sheet0.png",
		"images/spr_miss-sheet0.png",
		"images/highscore-sheet0.png",
		"images/score-sheet0.png",
		"images/spr_digismile-sheet0.png",
		"images/explode-sheet0.png",
		"images/explode-sheet1.png",
		"images/explode-sheet2.png",
		"images/btn_help-sheet0.png",
		"images/spr_help-sheet0.png",
		"media/explode.m4a",
		"media/explode.ogg",
		"media/eat.m4a",
		"media/eat.ogg",
		"media/eating-hard-vegetable.m4a",
		"media/eating-hard-vegetable.ogg",
		"media/xylo-miss-ding.m4a",
		"media/xylo-miss-ding.ogg",
		"media/funny gp 006.m4a",
		"media/funny gp 006.ogg",
		"media/funny gp 003.m4a",
		"media/funny gp 003.ogg",
		"media/funny menu 004.m4a",
		"media/funny menu 004.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}